# Generated by Django 5.2.5 on 2025-08-06 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sumka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=110)),
                ('modele', models.TextField()),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rangi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rang', to='home.rang')),
            ],
        ),
    ]
